version: '3'

services:
  copier:
    image: golang:alpine
    restart: always
    volumes:
      - "./:/app"
    environment:
      - TARGET_USER=admin
      - TARGET_PASSWORD=admin
      - TARGET_HOST=127.0.0.1
      - TARGET_V_HOST=/live
      - TARGET_EXCHANGE_NAME=app
      - TARGET_ROUTING_KEY=products.*
      - SOURCE_USER=admin
      - SOURCE_PASSWORD=admin
      - SOURCE_HOST=127.0.0.1
      - SOURCE_V_HOST=/live
      - SOURCE_QUEUE_NAME=app2.products
    command: ["/app/rabbitmq-data-copier"]